import { Transaction } from "./columns";

export const mockTransactions: Transaction[] = [
    {
        id: "txn_001",
        date: new Date("2026-03-01T10:30:00Z"),
        description: "Monthly Rent Payment",
        creditingAccount: "Landlord Account",
        debitingAccount: "Checking Account",
        amount: 50000,
    },
    {
        id: "txn_002",
        date: new Date("2026-03-02T14:15:00Z"),
        description: "Grocery Shopping",
        creditingAccount: "Supermarket Ltd",
        debitingAccount: "Credit Card",
        amount: 8500,
    },
    {
        id: "txn_003",
        date: new Date("2026-03-03T09:00:00Z"),
        description: "Salary Credit",
        creditingAccount: "Savings Account",
        debitingAccount: "Employer Account",
        amount: 150000,
    },
    {
        id: "txn_004",
        date: new Date("2026-03-05T18:45:00Z"),
        description: "Electricity Bill",
        creditingAccount: "Ceylon Electricity Board",
        debitingAccount: "Checking Account",
        amount: 4200,
    },
    {
        id: "txn_005",
        date: new Date("2026-03-06T12:00:00Z"),
        description: "Restaurant Dine-in",
        creditingAccount: "Local Cafe",
        debitingAccount: "Credit Card",
        amount: 3500,
    },
    {
        id: "txn_006",
        date: new Date("2026-03-08T08:30:00Z"),
        description: "Internet Bill",
        creditingAccount: "Dialog Axiata",
        debitingAccount: "Checking Account",
        amount: 2500,
    },
    {
        id: "txn_007",
        date: new Date("2026-03-10T16:20:00Z"),
        description: "Fuel Station",
        creditingAccount: "Ceypetco",
        debitingAccount: "Credit Card",
        amount: 12000,
    },
    {
        id: "txn_008",
        date: new Date("2026-03-12T11:10:00Z"),
        description: "Online Shopping",
        creditingAccount: "Daraz",
        debitingAccount: "Credit Card",
        amount: 6800,
    },
    {
        id: "txn_009",
        date: new Date("2026-03-14T15:00:00Z"),
        description: "Medical Consultation",
        creditingAccount: "City Hospital",
        debitingAccount: "Checking Account",
        amount: 4000,
    },
    {
        id: "txn_010",
        date: new Date("2026-03-15T09:45:00Z"),
        description: "Freelance Payment",
        creditingAccount: "Savings Account",
        debitingAccount: "Client Account",
        amount: 45000,
    },
    {
        id: "txn_011",
        date: new Date("2026-03-18T13:30:00Z"),
        description: "Movie Tickets",
        creditingAccount: "Scope Cinemas",
        debitingAccount: "Credit Card",
        amount: 2400,
    },
    {
        id: "txn_012",
        date: new Date("2026-03-20T17:15:00Z"),
        description: "Gym Membership",
        creditingAccount: "Fitness First",
        debitingAccount: "Checking Account",
        amount: 8000,
    }
];
